### ISSUE TITLE
short reads not appearing in workload stats summary

### ISSUE THREAD

**Issue by ArnauPrat** [ldbc/ldbc_driver#48]
Hi

When running the benchmark with all the queries enables (complex reads, short reads and updates), using the -stats options, short reads are not appearing in the summary. However, it seems that they are executed, as our implementation receives calls to short reads.

Arnau

**Comment by mkaufmann** [comment]
Should be fixed now?

**Comment by alexaverbuch** [comment]
no, but thanks for reminding
FYI, @mkaufmann, this only applies to when you use `-stats`

**Comment by alexaverbuch** [comment]
Done
