### ISSUE TITLE
Hanging at: Client  Scanning workload streams to calculate their limits...

### ISSUE THREAD

**Issue by mirkospasic** [ldbc/ldbc_driver#49]
For SF300, at this stage it will hang more than 20minutes with this config:
	Name:                           LDBC
	DB:                             com.ldbc.driver.workloads.ldbc.snb.interactive.db.VirtuosoDb
	Workload:                       com.ldbc.driver.workloads.ldbc.snb.interactive.LdbcSnbInteractiveWorkload
	Operation Count:                1,000
	Worker Threads:                 1
	Status Display Interval:        00:02.000.000 (m:s.ms.us)
	Time Unit:                      MILLISECONDS
	Results Directory:              /home/sib300/driver/results
	Create Results Log:             false
	Time Compression Ratio:         0.0001000
	Peer IDs:                       []
	Validation Creation Params:     null
	Database Validation File:       null
	Validate Workload:              false
	Calculate Workload Statistics:  false
	Spinner Sleep Duration:         00:00.000.000 (m:s.ms.us) / 0 (ms)
	Print Help:                     false
	Ignore Scheduled Start Times:   false
	User-defined parameters:
		endpoint = localhost:1210
		ldbc.snb.interactive.LdbcQuery10_enable = false
		ldbc.snb.interactive.LdbcQuery10_freq = 329
		ldbc.snb.interactive.LdbcQuery10_interleave = 329
		ldbc.snb.interactive.LdbcQuery11_enable = false
		ldbc.snb.interactive.LdbcQuery11_freq = 371
		ldbc.snb.interactive.LdbcQuery11_interleave = 371
		ldbc.snb.interactive.LdbcQuery12_enable = false
		ldbc.snb.interactive.LdbcQuery12_freq = 407
		ldbc.snb.interactive.LdbcQuery12_interleave = 407
		ldbc.snb.interactive.LdbcQuery13_enable = false
		ldbc.snb.interactive.LdbcQuery13_freq = 413
		ldbc.snb.interactive.LdbcQuery13_interleave = 413
		ldbc.snb.interactive.LdbcQuery14_enable = false
		ldbc.snb.interactive.LdbcQuery14_freq = 748
		ldbc.snb.interactive.LdbcQuery14_interleave = 748
		ldbc.snb.interactive.LdbcQuery1_enable = false
		ldbc.snb.interactive.LdbcQuery1_freq = 255
		ldbc.snb.interactive.LdbcQuery1_interleave = 255
		ldbc.snb.interactive.LdbcQuery2_enable = true
		ldbc.snb.interactive.LdbcQuery2_freq = 500
		ldbc.snb.interactive.LdbcQuery2_interleave = 500
		ldbc.snb.interactive.LdbcQuery3_enable = false
		ldbc.snb.interactive.LdbcQuery3_freq = 1189
		ldbc.snb.interactive.LdbcQuery3_interleave = 1189
		ldbc.snb.interactive.LdbcQuery4_enable = false
		ldbc.snb.interactive.LdbcQuery4_freq = 421
		ldbc.snb.interactive.LdbcQuery4_interleave = 421
		ldbc.snb.interactive.LdbcQuery5_enable = false
		ldbc.snb.interactive.LdbcQuery5_freq = 877
		ldbc.snb.interactive.LdbcQuery5_interleave = 877
		ldbc.snb.interactive.LdbcQuery6_enable = false
		ldbc.snb.interactive.LdbcQuery6_freq = 3728
		ldbc.snb.interactive.LdbcQuery6_interleave = 3728
		ldbc.snb.interactive.LdbcQuery7_enable = false
		ldbc.snb.interactive.LdbcQuery7_freq = 432
		ldbc.snb.interactive.LdbcQuery7_interleave = 432
		ldbc.snb.interactive.LdbcQuery8_enable = false
		ldbc.snb.interactive.LdbcQuery8_freq = 34
		ldbc.snb.interactive.LdbcQuery8_interleave = 34
		ldbc.snb.interactive.LdbcQuery9_enable = false
		ldbc.snb.interactive.LdbcQuery9_freq = 3709
		ldbc.snb.interactive.LdbcQuery9_interleave = 3709
		ldbc.snb.interactive.LdbcShortQuery1PersonProfile_enable = false
		ldbc.snb.interactive.LdbcShortQuery2PersonPosts_enable = false
		ldbc.snb.interactive.LdbcShortQuery3PersonFriends_enable = false
		ldbc.snb.interactive.LdbcShortQuery4MessageContent_enable = false
		ldbc.snb.interactive.LdbcShortQuery5MessageCreator_enable = false
		ldbc.snb.interactive.LdbcShortQuery6MessageForum_enable = false
		ldbc.snb.interactive.LdbcShortQuery7MessageReplies_enable = false
		ldbc.snb.interactive.LdbcUpdate1AddPerson_enable = false
		ldbc.snb.interactive.LdbcUpdate2AddPostLike_enable = false
		ldbc.snb.interactive.LdbcUpdate3AddCommentLike_enable = false
		ldbc.snb.interactive.LdbcUpdate4AddForum_enable = false
		ldbc.snb.interactive.LdbcUpdate5AddForumMembership_enable = false
		ldbc.snb.interactive.LdbcUpdate6AddPost_enable = false
		ldbc.snb.interactive.LdbcUpdate7AddComment_enable = false
		ldbc.snb.interactive.LdbcUpdate8AddFriendship_enable = false
		ldbc.snb.interactive.data_dir = /2d6/mirkoOutputDir/300sf_csv
		ldbc.snb.interactive.gct_delta_duration = 10000
		ldbc.snb.interactive.max_write_event_start_time = 1359673209655
		ldbc.snb.interactive.min_write_event_start_time = 1350748089001
		ldbc.snb.interactive.num_events = 877373396
		ldbc.snb.interactive.parameters_dir = /2d6/mirkoOutputDir/300sf_csv/substitution_parameters
		ldbc.snb.interactive.update_interleave = 1
		password = dba
		printQueryNames = false
		printQueryResults = false
		printQueryStrings = false
		queryDir = /2d1/ldbc/ldbc_snb_interactive_vendors/interactive/virtuoso/queries/sql
		run_sql = true
		user = dba

If I don't specify the updates dir, it will not happen.

**Comment by alexaverbuch** [comment]
solved
