### ISSUE TITLE
Short Query 3 validation is false

### ISSUE THREAD

**Issue by tomersagi** [ldbc/ldbc_driver#52]
Hi,
I'm getting the following result when validation short query 3:

```
Operation:        LdbcShortQuery3PersonFriends{personId=5497558139396}
    Expected Result:  [LdbcShortQuery3PersonFriendsResult{personId=864, firstName='Vladimir', lastName='Foxx', friendshipCreationDate=1293955806031}, LdbcShortQuery3PersonFriendsResult{personId=864, firstName='Vladimir', lastName='Foxx', friendshipCreationDate=1293955806031}]
    Actual Result  :  [LdbcShortQuery3PersonFriendsResult{personId=864, firstName='Vladimir', lastName='Foxx', friendshipCreationDate=1293955806031}]
```

The query is supposed to return a person's friends, I assume once?
Thanks,
Tomer

**Comment by alexaverbuch** [comment]
please update your LDBC Driver repository _and_ your validation repository, I suspect you have an old version of the validation repository - how many operations are in the validation parameters file?

**Comment by alexaverbuch** [comment]
This was a real issue. the expected results did not filter out duplicates. fixed now.
Also, in future please report these issues to the validation repository.
Thanks @tomersagi
