### ISSUE TITLE
Unexplained driver crash

### ISSUE THREAD

**Issue by tomersagi** [ldbc/ldbc_driver#59]
New issue,
Dirver runs ok single-threaded, when I allow 12 worker threads (I have 24 cores, should be ok in that respect) after a couple of minutes of smooth sailing, I get the following error log:

```
Shutting down status thread...
ExecuteWorkloadMode  Shutting down workload...
Client  Client terminated unexpectedly
com.ldbc.driver.ClientException: Error running workload
	at com.ldbc.driver.client.ExecuteWorkloadMode.doExecute(ExecuteWorkloadMode.java:394)
	at com.ldbc.driver.client.ExecuteWorkloadMode.startExecutionAndAwaitCompletion(ExecuteWorkloadMode.java:127)
	at com.ldbc.driver.Client.main(Client.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: com.ldbc.driver.ClientException: Error running workload

- Start Error Log -
	SOURCE:	WorkloadRunnerThread [518] (Thread: ID=15, Name=Thread-2, Priority=5)
	ERROR:	Encountered error while shutting down
com.ldbc.driver.runtime.executor.OperationExecutorException: Error encountered while trying to shutdown
	at com.ldbc.driver.runtime.executor.ThreadPoolOperationExecutor.shutdown(ThreadPoolOperationExecutor.java:133)
	at com.ldbc.driver.runtime.WorkloadRunner$WorkloadRunnerThread.shutdownEverything(WorkloadRunner.java:510)
	at com.ldbc.driver.runtime.WorkloadRunner$WorkloadRunnerThread.run(WorkloadRunner.java:451)
Caused by: com.ldbc.driver.runtime.executor.OperationExecutorException: ThreadPoolOperationExecutor shutdown before all handlers could complete
422 handlers were queued for execution but not yet started
12 handlers were mid-execution
	at com.ldbc.driver.runtime.executor.ThreadPoolOperationExecutor.shutdown(ThreadPoolOperationExecutor.java:127)
	... 2 more

- End Error Log -
```

From this output I can't understand the source of the crash, could you hep me out?
Thanks
Tomer

**Comment by tomersagi** [comment]
As per https://github.com/ldbc/ldbc_driver/issues/58#issuecomment-141897580 I'll try rethrowing a DbException in all of my handlers, and see if it improves the error report

**Comment by alexaverbuch** [comment]
Does this occur at the end of the workload?
E.g., after the benchmark has completed, all/most operations?

**Comment by tomersagi** [comment]
Nope, somewhere in the middle. I ran it with oc=5000 and it crashed after ~1000 were completed. Also, rethrowing DbException didn't improve error readability.

**Comment by alexaverbuch** [comment]
@tomersagi to try to track down your issue I'm now running multiple variants (readonly, writeonly, full) of LDBC Interactive against multiple versions (2.1-2.3) of Neo4j using a number (Cypher, Java) of connectors. These builds are running continuously in our CI environment. So far the issue has not shown up, but I'll keep trying.
In the mean time, any additional information from your end would be great. E.g.

  1. does it *always* work fine with 1 thread?
  2. does it *always* fail with > 1 thread?
  3. do you see any other clues?

**Comment by tomersagi** [comment]
Well, after throwing the DbException in all the handlesr, it now crashes consistently on any number of threads. on single thread it seems that it crashes following Query 4. I don't know why, I'll add debug statements to Q4 and see where and why it crashes, but it would be usefull to get the error info from the driver.

**Comment by alexaverbuch** [comment]
agree 100% with
> but it would be useful to get the error info from the driver

if you can track down the cause of the crash and then let me know what you find I'll update the driver to catch and report on that failure case

**Comment by tomersagi** [comment]
ok, cause is an uncaught TitanException from here: https://github.com/ldbc/ldbc_snb_implementations/blob/master/interactive/titan/titanFTM_driver/src/main/java/hpl/alp2/titan/drivers/interactive/LdbcQuery4Handler.java#L63
Should I catch it and rethrow a DbException?

**Comment by alexaverbuch** [comment]
@tomersagi in general my preference is to catch the exceptions that I know will happen, as I like my code to act accordingly. that said, the driver should be displaying this error.
do you mind sharing the ENTIRE printout for when these crashes happen please?

**Comment by tomersagi** [comment]
sure: http://pastebin.com/EvyJZt62

**Comment by alexaverbuch** [comment]
@tomersagi I've pushed more changes to the driver, please let me know if it now picks up your exception and reports it in the log

**Comment by alexaverbuch** [comment]
@tomersagi I can confirm I'm seeing this weird behavior too. it doesn't appear in any of the driver tests, but it appears in the tests for my Neo4j connector. looking into it now.
in the mean time you might want to run against an older commit. I think this one predates the issue: https://github.com/ldbc/ldbc_driver/commit/d4dc3f9fabe6537696960b0738f0587b43b4bb1d

**Comment by alexaverbuch** [comment]
@tomersagi ok, please try the latest commit. I think the issue is resolved now

**Comment by tomersagi** [comment]
Looks resolved, now getting a nice fat error trace I can use to debug the new titan-mapdb backend with jan kotek...

**Comment by alexaverbuch** [comment]
great
